# syntax=docker/dockerfile:1

# ─────────────────────────────────────────────────────────────────────────────
#  Stage 1 — deps
#  Install production + dev dependencies with layer caching.
#  Re-runs only when package.json or package-lock.json changes.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# ─────────────────────────────────────────────────────────────────────────────
#  Stage 2 — builder
#  Compile the Next.js application.
#  NEXT_TELEMETRY_DISABLED suppresses the telemetry prompt during build.
#  Build-time env vars that are baked into the client bundle must be supplied
#  here; all server-only secrets are injected at runtime instead.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public env vars referenced in client components (NEXT_PUBLIC_*)
# These are NOT secrets — they become visible in the browser bundle.
ARG NEXT_PUBLIC_APP_NAME="Francine CRM"
ARG NEXT_PUBLIC_APP_URL="http://localhost:3000"

ENV NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production \
    NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME} \
    NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}

RUN npm run build

# ─────────────────────────────────────────────────────────────────────────────
#  Stage 3 — runner  (final image)
#  Uses the Next.js "standalone" output so only the minimal server bundle
#  is copied — no node_modules directory, no source files.
#  Final image is typically 150–250 MB vs 1+ GB for a naive copy.
# ─────────────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS runner

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Least-privilege: run as a non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy the standalone server bundle
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static assets and public folder
COPY --from=builder --chown=nextjs:nodejs /app/.next/static  ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public        ./public

USER nextjs

EXPOSE 3000

ENV PORT=3000 \
    HOSTNAME="0.0.0.0" \
    NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1

# next start is not used in standalone mode — the server entry point is
# .next/standalone/server.js, generated by next build with output: "standalone"
CMD ["node", "server.js"]
